# Generated by Django 5.1.1 on 2024-09-27 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=20)),
                ("autor", models.CharField(max_length=20)),
                ("descripcion", models.TextField()),
                ("fecha_agregado", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="libros/libro_default.png",
                        null=True,
                        upload_to="libros",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="libros.categoria",
                    ),
                ),
            ],
        ),
    ]
